### ISSUE TITLE
Support newest modelserver-theia concept

### ISSUE THREAD

**Issue by ndoschek** [eclipse-emfcloud/jsonforms-property-view#2]
- ModelserverAwareWidgetProvider should support updated emfcloud-modelserver-theia API (i.e. `updateViaCommand` should take `ModelServerMessage` as argument on incremental update instead of `ModelServerCommand`).
- Update emfcloud-modelserver-theia dependency

**Comment by tortmayr** [comment]
This was partly resolved with PR #3. The `ModelserverMessage` is parsed in `updateWidgetData` and then the `CommandExecutionResult` is passed to the `updateViaCommand` method.
