### ISSUE TITLE
Support webpack 5

### ISSUE THREAD

**Issue by tortmayr** [eclipse-emfcloud/jsonforms-property-view#4]
The latest Theia version (1.15.0) bumped Webpack to version 5.xx which leads to incompatibilities with the `json-forms-property-view` package. In version 5 they removed the default polyfill fallback for node.js defaults which is why this package throws errors when trying to build with webpack. This is caused by the json-forms dependency and should be fixed by upgrading to the latest alpha.

**Comment by martin-fleck-at** [comment]
Fixed with https://github.com/eclipse-emfcloud/jsonforms-property-view/commit/3a48b86a663ad6b06b02a86ab553132619ab1db4
